# Generated by Django 5.1.1 on 2024-12-23 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$d4riBeFtzRf6fSoptS84uQ$k9BaTiwVAt8/m8xT1NJEPog+NM9eZ/bF8GEFBLGo9Qw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_library.book'),
        ),
        migrations.CreateModel(
            name='RemovedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_isbn', models.CharField(default='UNKNOWN', max_length=13)),
                ('title', models.CharField(default='UNKNOWN', max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('date_removed', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_book_id', models.CharField(default='UNKNOWN', max_length=50)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_library.book')),
            ],
        ),
    ]
