# Generated by Django 5.1.1 on 2024-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0002_staff_user_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$bnv4cJV1bxRKAFGboZSM9I$oM6UfQytznoZ2Lepuq2/ckCzQKyrTpFhEuXWINuPyxM=', max_length=128),
        ),
    ]
