# Generated by Django 5.1.1 on 2024-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0003_alter_staff_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_admin_user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$71g7BGZ0gLKs8yGZhXh5vN$+eh8bNYfb4UvOnM2VUlfPODKGGwuBPcD9xBToNcu+Bk=', max_length=128),
        ),
    ]
