# Generated by Django 5.1.1 on 2024-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0005_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$yVe51bjsltSHwbpC4TDcwz$cOOmp4naPijGUJsPV6DxRpLoVpsEkJ1iOUwTIzJQGCU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Is Admin User'),
        ),
    ]
