# Generated by Django 5.1.1 on 2024-12-23 15:17

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0007_alter_staff_password_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='TEMP_ADMIN_ID', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 23, 15, 16, 52, 863766, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JIOSHSgiFW8mGZBfUXeDgA$nn7PlTtDMaX3/ZsfpbAPAdEf0CITys+wnei8Es4+p9U=', max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$q8pmVZlIYdQDd1kwr6Mkbe$2oLK4HGj5iPTKLfBHi8tS18tytw/xxT78WYObry8UsQ=', max_length=128),
        ),
        migrations.CreateModel(
            name='RemovedAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_admin_id', models.CharField(default='UNKNOWN', max_length=50)),
                ('admin_name', models.CharField(default='NULL', max_length=200)),
                ('date_removed', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_library.admin')),
            ],
        ),
    ]
