# Generated by Django 5.1.1 on 2024-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0008_admin_admin_id_admin_date_added_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin_user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$0qSBnKeiIvRvBBKNHfGldF$tt3qTVa2F7uDqr+qv2A8Ca6UYaFKmT60llxX3aVs4PE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$4W7oGqpSO8f5ThJNImwJD4$gV3PjfYOXROggZ+bjgrwe7C7g3L1u9N25pPfPL/iJRM=', max_length=128),
        ),
    ]
