# Generated by Django 5.1.1 on 2024-12-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0009_remove_user_is_admin_user_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fine',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='app_library.transaction'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8t0Zn5gTncHFL8PtLZls8R$7xilQfh0WVM6tFexfMe0CuF69Nwo3zV8rgiOSXOZD5o=', max_length=128),
        ),
        migrations.AlterField(
            model_name='fine',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fine',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BYgaOtg8SXo7Bk7XXqT5Md$nyx+5FjcrPUySHShE5FT+LWKEPmlYXDcZMIOBOZuTMY=', max_length=128),
        ),
    ]
