# Generated by Django 5.1.1 on 2025-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0010_fine_fine_amount_fine_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xoOBrZbc1PulZXySqNEQPV$sZjhXlO9eSnt1QVcxTWqwT9qMYvQ6lCXhGBABCz9AO8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xKVm7B9nAchIeYy8OTSaW7$D0S8+4YqYImtHG9lrcNzNUJq6KSQQvHPv61brQ32GcI=', max_length=128),
        ),
    ]
