# Generated by Django 5.1.1 on 2025-01-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0011_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$zRbv7vCLkuIXDoRovR8kZq$eIin/pCAjFz/mja3Wt6PP6Pfn8hUTo3jIZuL2gbOouw=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LnBjQlTAZsVL1pxXgrpFS4$JqQVAcP9Fa548GKy2b5mOIiLVGqZ8x+Vp1eGRLV5kLM=', max_length=128),
        ),
    ]
