# Generated by Django 5.1.1 on 2025-01-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0012_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$HDaFxcXEWw2hoJuSS74iGt$ITHtNVUunaNoLWrAVYKpI3ZouhTReBX2ZcjG7NZlNSE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KMjNMrUwn820pTTyXDqCQ9$v8fSPmp7F896DjWvvsntmSbucAxu8ZDmq/JxIidmgx8=', max_length=128),
        ),
    ]
