# Generated by Django 5.1.1 on 2025-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0015_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gNZD0h4SFEntLzJmoR6cPN$GbyHMWJPjEVmmhGY0dg/QHlaJZKJdPPIVtHXy5EjyTM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$OxI1GJAYshJqp5HmsFKMaJ$nIyn2lHU6Krmt9+9ig+c6e/9AWari1yqMGEr3Q0UXkg=', max_length=128),
        ),
    ]
