# Generated by Django 5.1.1 on 2025-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0016_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$aF9qLeUutm5N7BdjWlTgkW$jieUtWxVKykr9Bf5YVWTgSVmQ7xHH40SPSfQcHBx4UA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gMjeZM9X3t7o7qdDgXvpMv$x8qZuRYeaQuPAK6b9g2qpkvtuvlopmqm81E9ipG5WVw=', max_length=128),
        ),
    ]
