# Generated by Django 5.1.1 on 2025-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0017_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$y8IjxabdwtGsqKpABU650i$kExhcb2umWoqlPWpIzFy9Ru3g7Uxe6OSh+ETxxW+MWg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$UcF3WRjuT7JTi9h2stmABT$Xf+r8e4M6x4cf2uyVzhKmEgpkDRdD7UFt3EkLszNEJI=', max_length=128),
        ),
    ]
