# Generated by Django 5.1.1 on 2025-01-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0018_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BarEITGCbv6X4tTt91SAe0$FChXVfY+NEL7mdA3zsoT6Io/afHnmGCHxzcy9IbpqOo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gWEoL5XfM6tQyt05bUt4vd$CgL4yHEVIEumdAk4NSDOTuog04o5vYlBx2HIFqtXbCI=', max_length=128),
        ),
    ]
