# Generated by Django 5.1.2 on 2025-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0019_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$T6BdAdyWALxmRKeLrkBAim$pdO7tTtSSaoX4moyj1E3CoF16g9UrjKbIv0S320lKPI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$gcUATlKCXlFDevkORneXK7$TRsdc4gNkf0NgveSnSYH/dwLsKLN8DjqdrQN/XtgCxg=', max_length=128),
        ),
    ]
