# Generated by Django 5.1.1 on 2025-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0020_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$KGxaDhaeHEJwdlDfuU19DP$wr2+JAFxjEOfnnQHlpM1XHrpE0zGMlrjxtpPQdyPs5w=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$V4ijzSYHjKEsEX0htHq1LD$jif3E+NNC3aQJh2x5mEqrB+bXhX60+C3/aldwR05R8w=', max_length=128),
        ),
    ]
