# Generated by Django 5.1.1 on 2025-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0021_alter_admin_password_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$M1tA7WUHCSN8wjZkyPtKs9$kFqkVYjEZOaKU1RlNmXyIn4yPo99nmi8T5UIqZUlgto=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6h0BOKQkyfR28nSHnxEQgL$3RTE3j6zc39Z7pcU23dS4rGOUY9bmJ5xijpqLSDrpGE=', max_length=128),
        ),
    ]
